server:
  http:
    port: 8080
    read_timeout: 10s
    write_timeout: 10s
    idle_timeout: 120s
  grpc:
    port: 9090

database:
  driver: mysql
  dsn: root:root@tcp(mysql:3306)/shop_user?charset=utf8mb4&parseTime=True&loc=Local
  max_open_conns: 100
  max_idle_conns: 10
  conn_max_lifetime: 1h

redis:
  addr: redis:6379
  password: ""
  db: 0

mongodb:
  uri: "mongodb://mongodb:27017"
  database: "user_logs"
  timeout: 10s

jwt:
  secret: "your-jwt-secret-key-should-be-very-long-and-secure"
  access_token_ttl: 15m
  refresh_token_ttl: 7d
  verification_ttl: 5m

log:
  level: info
  format: json
  output: stdout
