# Profile Service Configuration

server:
  name: profile-service
  host: localhost
  port: 8024

mysql:
  host: localhost
  port: 3306
  username: root
  password: root
  database: shop_profile
  max_open_conns: 100
  max_idle_conns: 10
  conn_max_lifetime: 3600

mongodb:
  uri: mongodb://localhost:27017
  database: shop_profile
  max_pool_size: 100
  min_pool_size: 10

redis:
  host: localhost
  port: 6379
  password:
  db: 0

consul:
  host: localhost
  port: 8500

nacos:
  host: localhost
  port: 8848
  namespace_id: profile-service
  group: DEFAULT_GROUP
  data_id: profile-service.yaml

log:
  level: info
  path: logs/profile-service.log
  error_path: logs/profile-service.error.log
  format: json

jwt:
  secret_key: your-secret-key-here
  expires_time: 86400
  refresh_time: 604800

grpc:
  product_service:
    host: localhost
    port: 50052
  user_service:
    host: localhost
    port: 50051
